//
//  RotationModel.swift
//  
//
//  Created by Ege Aydin on 6/15/17.
//
//  This class is shared by both Mac and iOS App. This type is used for wrapping the x,y,z and the tracking speed that is desired to send to the driver

import Foundation

class XYZ: CustomStringConvertible
{
    var x: Double
    var y: Double
    var z: Double
    
    var trackSpeed: Double
    
    public var description: String { return "x:\(self.x),y:\(self.y),z:\(self.z),t:\(self.trackSpeed)" }
    
    /**
     Initializases a new package instance
     - Parameters:
         - x: desired X value
         - y: desired Y value
         - z: desired Z value
         - trackSpeed: desired Tracking Speed for mouse corsor
     */
    init(x: Double, y: Double, z: Double, trackSpeed: Double)
    {
        self.x = x
        self.y = y
        self.z = z
        self.trackSpeed = trackSpeed
    }
    
    /**
     Creates a new XYZ instance from an appropriate string.
     - Warning: This method will crash if the string is not correct.
     - Parameters:
         - string: The appropriate should be generated by converting this type to string
    */
    static func from(string: String) throws -> XYZ
    {
        let values = string.components(separatedBy: ",")
        
        var x = 0.0
        var y = 0.0
        var z = 0.0
        var trackSpeed = 0.0
        
        for pair in values
        {
            let p = pair.components(separatedBy: ":")
            let value = Double(p[1])!
            switch p[0]
            {
            case "x":
                x = value
            case "y":
                y = value
            case "z":
                z = value
            case "t":
                trackSpeed = value
            default:
                throw ConversionError.InvalidInputString("The input string has an invalid character: \(p[0])")
            }
        }
        
        return XYZ(x:x, y:y, z:z, trackSpeed: trackSpeed)
    }
}

enum ConversionError : Error {
    case InvalidInputString(String)
}
